name: 'Global Rust Compiler'
description: 'Cross-compiles binaries based on a JSON target map'

inputs:
  bin_name:
    description: 'Name of the binary to build'
    required: true

runs:
  using: "composite"
  steps:
    - name: Cache Cargo Dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cross-${{ inputs.bin_name }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cross-${{ inputs.bin_name }}-

    - name: Ensure Cross is installed
      shell: bash
      run: |
        if ! command -v cross &> /dev/null; then
          echo "::group::Installing Cross"
          curl -L https://github.com/cross-rs/cross/releases/latest/download/cross-x86_64-unknown-linux-musl.tar.gz | tar xz -C ~/.cargo/bin
          echo "::endgroup::"
        fi
  
    - shell: bash
      run: |
        MAP_PATH="${{ github.action_path }}/targets.json"
        
        for TARGET in $(jq -r 'keys[]' "$MAP_PATH"); do
          SHORT=$(jq -r ".\"$TARGET\"" "$MAP_PATH")
          
          EXT=""
          [[ "$TARGET" == *"windows"* ]] && EXT=".exe"
          
          echo "::group::Building $TARGET ($SHORT)"
          export CARGO_APP_VERSION="${GITHUB_REF_NAME#v}"
          cross build --release --target "$TARGET"
          cp "target/$TARGET/release/${{ inputs.bin_name }}$EXT" "${{ inputs.bin_name }}-$SHORT$EXT"
          echo "::endgroup::"
        done
